package team.burden.music.api;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import team.burden.music.api.model.Song;
import team.burden.music.api.protos.Grpc;
import team.burden.music.api.protos.GrpcServiceGrpc;
import team.burden.music.api.protos.Music;
import team.burden.music.api.util.ModelUtil;

@RunWith(SpringRunner.class)
@SpringBootTest
public class ApplicationTests {

    @Test
    public void contextLoads() {
    }

    @Test
    public void addSongTest() {
        ManagedChannel managedChannel = ManagedChannelBuilder.forAddress("localhost", 9090).usePlaintext().build();
        GrpcServiceGrpc.GrpcServiceBlockingStub grpcServiceBlockingStub = GrpcServiceGrpc.newBlockingStub(managedChannel);

        team.burden.music.api.protos.Grpc.AddSongRequest request = team.burden.music.api.protos.Grpc.AddSongRequest.newBuilder()
                .setSong(getDefaultSong()).buildPartial();
        System.out.println(grpcServiceBlockingStub.addSong(request).getResult());
    }

    @Test
    public void getSongsTest() {
        ManagedChannel managedChannel = ManagedChannelBuilder.forAddress("localhost", 9090).usePlaintext().build();
        GrpcServiceGrpc.GrpcServiceBlockingStub grpcServiceBlockingStub = GrpcServiceGrpc.newBlockingStub(managedChannel);

        team.burden.music.api.protos.Grpc.QuerySongsRequest request = team.burden.music.api.protos.Grpc.QuerySongsRequest.newBuilder()
                .setOffset(0)
                .setSize(10)
                .buildPartial();
        System.out.println(grpcServiceBlockingStub.querySongs(request));
    }

    @Test
    public void getSongTest() {
        ManagedChannel managedChannel = ManagedChannelBuilder.forAddress("localhost", 9090).usePlaintext().build();
        GrpcServiceGrpc.GrpcServiceBlockingStub grpcServiceBlockingStub = GrpcServiceGrpc.newBlockingStub(managedChannel);

        team.burden.music.api.protos.Grpc.QuerySongRequest request = team.burden.music.api.protos.Grpc.QuerySongRequest.newBuilder().setTitle("进击的巨人").buildPartial();
        Grpc.QuerySongResponse response = grpcServiceBlockingStub.querySong(request);
        Song song = ModelUtil.toModelSong(response.getSong());
        System.out.println(song);
        try {
            Music.Tones tones = Music.Tones.parseFrom((byte[]) song.getTones());
            System.out.println(tones);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Music.Song getDefaultSong() {
        Music.Tone.Builder toneBuilder;
        Music.Tones.Builder tonesBuilder = Music.Tones.newBuilder();
        Music.Song.Builder songBuilder = Music.Song.newBuilder();

        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(600);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(3);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(600);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(3);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(2);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(7);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(600);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(6);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(8);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(11);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(13);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(7);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(9);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(8);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(10);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(9);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(3);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.addTone(5);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(4);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(3);
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(7);
        toneBuilder.addTone(12);
        toneBuilder.addTone(14);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(6);
        toneBuilder.addTone(11);
        toneBuilder.addTone(13);
        toneBuilder.setDuration(400);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(2);
        toneBuilder.addTone(5);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(1);
        toneBuilder.addTone(4);
        toneBuilder.addTone(6);
        toneBuilder.addTone(8);
        toneBuilder.addTone(11);
        toneBuilder.setDuration(200);
        tonesBuilder.addTones(toneBuilder.build());
        toneBuilder = Music.Tone.newBuilder();
        toneBuilder.addTone(0);
        toneBuilder.addTone(2);
        toneBuilder.addTone(7);
        toneBuilder.addTone(9);
        toneBuilder.addTone(12);
        toneBuilder.setDuration(100);
        tonesBuilder.addTones(toneBuilder.build());

        songBuilder.setDuration(66300);
        songBuilder.setTitle("进击的巨人");
        songBuilder.setCreator("白狼");
        songBuilder.setTones(tonesBuilder.build().toByteString());
        return songBuilder.build();
    }

}
