// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package team.burden.music.api.protos;

public final class Music {
  private Music() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Song)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string creator = 2;</code>
     * @return The creator.
     */
    java.lang.String getCreator();
    /**
     * <code>string creator = 2;</code>
     * @return The bytes for creator.
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <code>int32 duration = 3;</code>
     * @return The duration.
     */
    int getDuration();

    /**
     * <code>bytes tones = 4;</code>
     * @return The tones.
     */
    com.google.protobuf.ByteString getTones();
  }
  /**
   * Protobuf type {@code Song}
   */
  public static final class Song extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Song)
      SongOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Song.newBuilder() to construct.
    private Song(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Song() {
      title_ = "";
      creator_ = "";
      tones_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Song();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Song(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
            case 24: {

              duration_ = input.readInt32();
              break;
            }
            case 34: {

              tones_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return team.burden.music.api.protos.Music.internal_static_Song_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return team.burden.music.api.protos.Music.internal_static_Song_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              team.burden.music.api.protos.Music.Song.class, team.burden.music.api.protos.Music.Song.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object creator_;
    /**
     * <code>string creator = 2;</code>
     * @return The creator.
     */
    @java.lang.Override
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>string creator = 2;</code>
     * @return The bytes for creator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 3;
    private int duration_;
    /**
     * <code>int32 duration = 3;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return duration_;
    }

    public static final int TONES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString tones_;
    /**
     * <code>bytes tones = 4;</code>
     * @return The tones.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTones() {
      return tones_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creator_);
      }
      if (duration_ != 0) {
        output.writeInt32(3, duration_);
      }
      if (!tones_.isEmpty()) {
        output.writeBytes(4, tones_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creator_);
      }
      if (duration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, duration_);
      }
      if (!tones_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, tones_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof team.burden.music.api.protos.Music.Song)) {
        return super.equals(obj);
      }
      team.burden.music.api.protos.Music.Song other = (team.burden.music.api.protos.Music.Song) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getCreator()
          .equals(other.getCreator())) return false;
      if (getDuration()
          != other.getDuration()) return false;
      if (!getTones()
          .equals(other.getTones())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
      hash = (37 * hash) + TONES_FIELD_NUMBER;
      hash = (53 * hash) + getTones().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static team.burden.music.api.protos.Music.Song parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Song parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Song parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Song parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(team.burden.music.api.protos.Music.Song prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Song}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Song)
        team.burden.music.api.protos.Music.SongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return team.burden.music.api.protos.Music.internal_static_Song_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return team.burden.music.api.protos.Music.internal_static_Song_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                team.burden.music.api.protos.Music.Song.class, team.burden.music.api.protos.Music.Song.Builder.class);
      }

      // Construct using team.burden.music.api.protos.Music.Song.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        creator_ = "";

        duration_ = 0;

        tones_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return team.burden.music.api.protos.Music.internal_static_Song_descriptor;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Song getDefaultInstanceForType() {
        return team.burden.music.api.protos.Music.Song.getDefaultInstance();
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Song build() {
        team.burden.music.api.protos.Music.Song result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Song buildPartial() {
        team.burden.music.api.protos.Music.Song result = new team.burden.music.api.protos.Music.Song(this);
        result.title_ = title_;
        result.creator_ = creator_;
        result.duration_ = duration_;
        result.tones_ = tones_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof team.burden.music.api.protos.Music.Song) {
          return mergeFrom((team.burden.music.api.protos.Music.Song)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(team.burden.music.api.protos.Music.Song other) {
        if (other == team.burden.music.api.protos.Music.Song.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        if (other.getDuration() != 0) {
          setDuration(other.getDuration());
        }
        if (other.getTones() != com.google.protobuf.ByteString.EMPTY) {
          setTones(other.getTones());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        team.burden.music.api.protos.Music.Song parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (team.burden.music.api.protos.Music.Song) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <code>string creator = 2;</code>
       * @return The creator.
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string creator = 2;</code>
       * @return The bytes for creator.
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string creator = 2;</code>
       * @param value The creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreator() {
        
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 2;</code>
       * @param value The bytes for creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creator_ = value;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>int32 duration = 3;</code>
       * @return The duration.
       */
      @java.lang.Override
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>int32 duration = 3;</code>
       * @param value The duration to set.
       * @return This builder for chaining.
       */
      public Builder setDuration(int value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 duration = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDuration() {
        
        duration_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tones_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tones = 4;</code>
       * @return The tones.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTones() {
        return tones_;
      }
      /**
       * <code>bytes tones = 4;</code>
       * @param value The tones to set.
       * @return This builder for chaining.
       */
      public Builder setTones(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tones_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tones = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTones() {
        
        tones_ = getDefaultInstance().getTones();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Song)
    }

    // @@protoc_insertion_point(class_scope:Song)
    private static final team.burden.music.api.protos.Music.Song DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new team.burden.music.api.protos.Music.Song();
    }

    public static team.burden.music.api.protos.Music.Song getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Song>
        PARSER = new com.google.protobuf.AbstractParser<Song>() {
      @java.lang.Override
      public Song parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Song(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Song> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Song> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public team.burden.music.api.protos.Music.Song getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TonesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tones)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    java.util.List<team.burden.music.api.protos.Music.Tone> 
        getTonesList();
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    team.burden.music.api.protos.Music.Tone getTones(int index);
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    int getTonesCount();
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    java.util.List<? extends team.burden.music.api.protos.Music.ToneOrBuilder> 
        getTonesOrBuilderList();
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    team.burden.music.api.protos.Music.ToneOrBuilder getTonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Tones}
   */
  public static final class Tones extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tones)
      TonesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tones.newBuilder() to construct.
    private Tones(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tones() {
      tones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tones();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tones(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tones_ = new java.util.ArrayList<team.burden.music.api.protos.Music.Tone>();
                mutable_bitField0_ |= 0x00000001;
              }
              tones_.add(
                  input.readMessage(team.burden.music.api.protos.Music.Tone.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tones_ = java.util.Collections.unmodifiableList(tones_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return team.burden.music.api.protos.Music.internal_static_Tones_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return team.burden.music.api.protos.Music.internal_static_Tones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              team.burden.music.api.protos.Music.Tones.class, team.burden.music.api.protos.Music.Tones.Builder.class);
    }

    public static final int TONES_FIELD_NUMBER = 1;
    private java.util.List<team.burden.music.api.protos.Music.Tone> tones_;
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    @java.lang.Override
    public java.util.List<team.burden.music.api.protos.Music.Tone> getTonesList() {
      return tones_;
    }
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends team.burden.music.api.protos.Music.ToneOrBuilder> 
        getTonesOrBuilderList() {
      return tones_;
    }
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    @java.lang.Override
    public int getTonesCount() {
      return tones_.size();
    }
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    @java.lang.Override
    public team.burden.music.api.protos.Music.Tone getTones(int index) {
      return tones_.get(index);
    }
    /**
     * <code>repeated .Tone tones = 1;</code>
     */
    @java.lang.Override
    public team.burden.music.api.protos.Music.ToneOrBuilder getTonesOrBuilder(
        int index) {
      return tones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tones_.size(); i++) {
        output.writeMessage(1, tones_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tones_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof team.burden.music.api.protos.Music.Tones)) {
        return super.equals(obj);
      }
      team.burden.music.api.protos.Music.Tones other = (team.burden.music.api.protos.Music.Tones) obj;

      if (!getTonesList()
          .equals(other.getTonesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTonesCount() > 0) {
        hash = (37 * hash) + TONES_FIELD_NUMBER;
        hash = (53 * hash) + getTonesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static team.burden.music.api.protos.Music.Tones parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tones parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tones parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tones parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(team.burden.music.api.protos.Music.Tones prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tones}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tones)
        team.burden.music.api.protos.Music.TonesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return team.burden.music.api.protos.Music.internal_static_Tones_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return team.burden.music.api.protos.Music.internal_static_Tones_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                team.burden.music.api.protos.Music.Tones.class, team.burden.music.api.protos.Music.Tones.Builder.class);
      }

      // Construct using team.burden.music.api.protos.Music.Tones.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTonesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (tonesBuilder_ == null) {
          tones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tonesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return team.burden.music.api.protos.Music.internal_static_Tones_descriptor;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tones getDefaultInstanceForType() {
        return team.burden.music.api.protos.Music.Tones.getDefaultInstance();
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tones build() {
        team.burden.music.api.protos.Music.Tones result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tones buildPartial() {
        team.burden.music.api.protos.Music.Tones result = new team.burden.music.api.protos.Music.Tones(this);
        int from_bitField0_ = bitField0_;
        if (tonesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tones_ = java.util.Collections.unmodifiableList(tones_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tones_ = tones_;
        } else {
          result.tones_ = tonesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof team.burden.music.api.protos.Music.Tones) {
          return mergeFrom((team.burden.music.api.protos.Music.Tones)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(team.burden.music.api.protos.Music.Tones other) {
        if (other == team.burden.music.api.protos.Music.Tones.getDefaultInstance()) return this;
        if (tonesBuilder_ == null) {
          if (!other.tones_.isEmpty()) {
            if (tones_.isEmpty()) {
              tones_ = other.tones_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTonesIsMutable();
              tones_.addAll(other.tones_);
            }
            onChanged();
          }
        } else {
          if (!other.tones_.isEmpty()) {
            if (tonesBuilder_.isEmpty()) {
              tonesBuilder_.dispose();
              tonesBuilder_ = null;
              tones_ = other.tones_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTonesFieldBuilder() : null;
            } else {
              tonesBuilder_.addAllMessages(other.tones_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        team.burden.music.api.protos.Music.Tones parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (team.burden.music.api.protos.Music.Tones) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<team.burden.music.api.protos.Music.Tone> tones_ =
        java.util.Collections.emptyList();
      private void ensureTonesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tones_ = new java.util.ArrayList<team.burden.music.api.protos.Music.Tone>(tones_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          team.burden.music.api.protos.Music.Tone, team.burden.music.api.protos.Music.Tone.Builder, team.burden.music.api.protos.Music.ToneOrBuilder> tonesBuilder_;

      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public java.util.List<team.burden.music.api.protos.Music.Tone> getTonesList() {
        if (tonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tones_);
        } else {
          return tonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public int getTonesCount() {
        if (tonesBuilder_ == null) {
          return tones_.size();
        } else {
          return tonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public team.burden.music.api.protos.Music.Tone getTones(int index) {
        if (tonesBuilder_ == null) {
          return tones_.get(index);
        } else {
          return tonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder setTones(
          int index, team.burden.music.api.protos.Music.Tone value) {
        if (tonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTonesIsMutable();
          tones_.set(index, value);
          onChanged();
        } else {
          tonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder setTones(
          int index, team.burden.music.api.protos.Music.Tone.Builder builderForValue) {
        if (tonesBuilder_ == null) {
          ensureTonesIsMutable();
          tones_.set(index, builderForValue.build());
          onChanged();
        } else {
          tonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder addTones(team.burden.music.api.protos.Music.Tone value) {
        if (tonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTonesIsMutable();
          tones_.add(value);
          onChanged();
        } else {
          tonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder addTones(
          int index, team.burden.music.api.protos.Music.Tone value) {
        if (tonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTonesIsMutable();
          tones_.add(index, value);
          onChanged();
        } else {
          tonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder addTones(
          team.burden.music.api.protos.Music.Tone.Builder builderForValue) {
        if (tonesBuilder_ == null) {
          ensureTonesIsMutable();
          tones_.add(builderForValue.build());
          onChanged();
        } else {
          tonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder addTones(
          int index, team.burden.music.api.protos.Music.Tone.Builder builderForValue) {
        if (tonesBuilder_ == null) {
          ensureTonesIsMutable();
          tones_.add(index, builderForValue.build());
          onChanged();
        } else {
          tonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder addAllTones(
          java.lang.Iterable<? extends team.burden.music.api.protos.Music.Tone> values) {
        if (tonesBuilder_ == null) {
          ensureTonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tones_);
          onChanged();
        } else {
          tonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder clearTones() {
        if (tonesBuilder_ == null) {
          tones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public Builder removeTones(int index) {
        if (tonesBuilder_ == null) {
          ensureTonesIsMutable();
          tones_.remove(index);
          onChanged();
        } else {
          tonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public team.burden.music.api.protos.Music.Tone.Builder getTonesBuilder(
          int index) {
        return getTonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public team.burden.music.api.protos.Music.ToneOrBuilder getTonesOrBuilder(
          int index) {
        if (tonesBuilder_ == null) {
          return tones_.get(index);  } else {
          return tonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public java.util.List<? extends team.burden.music.api.protos.Music.ToneOrBuilder> 
           getTonesOrBuilderList() {
        if (tonesBuilder_ != null) {
          return tonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tones_);
        }
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public team.burden.music.api.protos.Music.Tone.Builder addTonesBuilder() {
        return getTonesFieldBuilder().addBuilder(
            team.burden.music.api.protos.Music.Tone.getDefaultInstance());
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public team.burden.music.api.protos.Music.Tone.Builder addTonesBuilder(
          int index) {
        return getTonesFieldBuilder().addBuilder(
            index, team.burden.music.api.protos.Music.Tone.getDefaultInstance());
      }
      /**
       * <code>repeated .Tone tones = 1;</code>
       */
      public java.util.List<team.burden.music.api.protos.Music.Tone.Builder> 
           getTonesBuilderList() {
        return getTonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          team.burden.music.api.protos.Music.Tone, team.burden.music.api.protos.Music.Tone.Builder, team.burden.music.api.protos.Music.ToneOrBuilder> 
          getTonesFieldBuilder() {
        if (tonesBuilder_ == null) {
          tonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              team.burden.music.api.protos.Music.Tone, team.burden.music.api.protos.Music.Tone.Builder, team.burden.music.api.protos.Music.ToneOrBuilder>(
                  tones_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tones_ = null;
        }
        return tonesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tones)
    }

    // @@protoc_insertion_point(class_scope:Tones)
    private static final team.burden.music.api.protos.Music.Tones DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new team.burden.music.api.protos.Music.Tones();
    }

    public static team.burden.music.api.protos.Music.Tones getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tones>
        PARSER = new com.google.protobuf.AbstractParser<Tones>() {
      @java.lang.Override
      public Tones parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tones(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tones> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tones> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public team.burden.music.api.protos.Music.Tones getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ToneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 tone = 1;</code>
     * @return A list containing the tone.
     */
    java.util.List<java.lang.Integer> getToneList();
    /**
     * <code>repeated int32 tone = 1;</code>
     * @return The count of tone.
     */
    int getToneCount();
    /**
     * <code>repeated int32 tone = 1;</code>
     * @param index The index of the element to return.
     * @return The tone at the given index.
     */
    int getTone(int index);

    /**
     * <code>int32 duration = 2;</code>
     * @return The duration.
     */
    int getDuration();
  }
  /**
   * Protobuf type {@code Tone}
   */
  public static final class Tone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tone)
      ToneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tone.newBuilder() to construct.
    private Tone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tone() {
      tone_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tone_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              tone_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                tone_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                tone_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {

              duration_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tone_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return team.burden.music.api.protos.Music.internal_static_Tone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return team.burden.music.api.protos.Music.internal_static_Tone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              team.burden.music.api.protos.Music.Tone.class, team.burden.music.api.protos.Music.Tone.Builder.class);
    }

    public static final int TONE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList tone_;
    /**
     * <code>repeated int32 tone = 1;</code>
     * @return A list containing the tone.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getToneList() {
      return tone_;
    }
    /**
     * <code>repeated int32 tone = 1;</code>
     * @return The count of tone.
     */
    public int getToneCount() {
      return tone_.size();
    }
    /**
     * <code>repeated int32 tone = 1;</code>
     * @param index The index of the element to return.
     * @return The tone at the given index.
     */
    public int getTone(int index) {
      return tone_.getInt(index);
    }
    private int toneMemoizedSerializedSize = -1;

    public static final int DURATION_FIELD_NUMBER = 2;
    private int duration_;
    /**
     * <code>int32 duration = 2;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return duration_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getToneList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(toneMemoizedSerializedSize);
      }
      for (int i = 0; i < tone_.size(); i++) {
        output.writeInt32NoTag(tone_.getInt(i));
      }
      if (duration_ != 0) {
        output.writeInt32(2, duration_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tone_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(tone_.getInt(i));
        }
        size += dataSize;
        if (!getToneList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        toneMemoizedSerializedSize = dataSize;
      }
      if (duration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, duration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof team.burden.music.api.protos.Music.Tone)) {
        return super.equals(obj);
      }
      team.burden.music.api.protos.Music.Tone other = (team.burden.music.api.protos.Music.Tone) obj;

      if (!getToneList()
          .equals(other.getToneList())) return false;
      if (getDuration()
          != other.getDuration()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getToneCount() > 0) {
        hash = (37 * hash) + TONE_FIELD_NUMBER;
        hash = (53 * hash) + getToneList().hashCode();
      }
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static team.burden.music.api.protos.Music.Tone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static team.burden.music.api.protos.Music.Tone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(team.burden.music.api.protos.Music.Tone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tone)
        team.burden.music.api.protos.Music.ToneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return team.burden.music.api.protos.Music.internal_static_Tone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return team.burden.music.api.protos.Music.internal_static_Tone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                team.burden.music.api.protos.Music.Tone.class, team.burden.music.api.protos.Music.Tone.Builder.class);
      }

      // Construct using team.burden.music.api.protos.Music.Tone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tone_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        duration_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return team.burden.music.api.protos.Music.internal_static_Tone_descriptor;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tone getDefaultInstanceForType() {
        return team.burden.music.api.protos.Music.Tone.getDefaultInstance();
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tone build() {
        team.burden.music.api.protos.Music.Tone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public team.burden.music.api.protos.Music.Tone buildPartial() {
        team.burden.music.api.protos.Music.Tone result = new team.burden.music.api.protos.Music.Tone(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          tone_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tone_ = tone_;
        result.duration_ = duration_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof team.burden.music.api.protos.Music.Tone) {
          return mergeFrom((team.burden.music.api.protos.Music.Tone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(team.burden.music.api.protos.Music.Tone other) {
        if (other == team.burden.music.api.protos.Music.Tone.getDefaultInstance()) return this;
        if (!other.tone_.isEmpty()) {
          if (tone_.isEmpty()) {
            tone_ = other.tone_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToneIsMutable();
            tone_.addAll(other.tone_);
          }
          onChanged();
        }
        if (other.getDuration() != 0) {
          setDuration(other.getDuration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        team.burden.music.api.protos.Music.Tone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (team.burden.music.api.protos.Music.Tone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList tone_ = emptyIntList();
      private void ensureToneIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tone_ = mutableCopy(tone_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @return A list containing the tone.
       */
      public java.util.List<java.lang.Integer>
          getToneList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(tone_) : tone_;
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @return The count of tone.
       */
      public int getToneCount() {
        return tone_.size();
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @param index The index of the element to return.
       * @return The tone at the given index.
       */
      public int getTone(int index) {
        return tone_.getInt(index);
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @param index The index to set the value at.
       * @param value The tone to set.
       * @return This builder for chaining.
       */
      public Builder setTone(
          int index, int value) {
        ensureToneIsMutable();
        tone_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @param value The tone to add.
       * @return This builder for chaining.
       */
      public Builder addTone(int value) {
        ensureToneIsMutable();
        tone_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @param values The tone to add.
       * @return This builder for chaining.
       */
      public Builder addAllTone(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tone_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tone = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTone() {
        tone_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>int32 duration = 2;</code>
       * @return The duration.
       */
      @java.lang.Override
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>int32 duration = 2;</code>
       * @param value The duration to set.
       * @return This builder for chaining.
       */
      public Builder setDuration(int value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 duration = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDuration() {
        
        duration_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tone)
    }

    // @@protoc_insertion_point(class_scope:Tone)
    private static final team.burden.music.api.protos.Music.Tone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new team.burden.music.api.protos.Music.Tone();
    }

    public static team.burden.music.api.protos.Music.Tone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tone>
        PARSER = new com.google.protobuf.AbstractParser<Tone>() {
      @java.lang.Override
      public Tone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public team.burden.music.api.protos.Music.Tone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Song_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Song_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tones_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tones_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Music.proto\"G\n\004Song\022\r\n\005title\030\001 \001(\t\022\017\n\007" +
      "creator\030\002 \001(\t\022\020\n\010duration\030\003 \001(\005\022\r\n\005tones" +
      "\030\004 \001(\014\"\035\n\005Tones\022\024\n\005tones\030\001 \003(\0132\005.Tone\"&\n" +
      "\004Tone\022\014\n\004tone\030\001 \003(\005\022\020\n\010duration\030\002 \001(\005B\036\n" +
      "\034team.burden.music.api.protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Song_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Song_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Song_descriptor,
        new java.lang.String[] { "Title", "Creator", "Duration", "Tones", });
    internal_static_Tones_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Tones_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tones_descriptor,
        new java.lang.String[] { "Tones", });
    internal_static_Tone_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Tone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tone_descriptor,
        new java.lang.String[] { "Tone", "Duration", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
